gem "haml", "2.2.15" 
gem "monk-glue" 
gem "do_sqlite3", "0.10.0" 
gem "dm-core", "0.10.2"
gem "dm-validations", "0.10.2"
gem "dm-timestamps", "0.10.2"
gem "warden", "0.8.1"
gem "rack", "1.0.1"
gem "rack-test", "0.5.3" 
gem "sinatra_warden"
gem "racksh", "0.9.4.2"
gem "json", "1.2.0"
gem "haml", "2.2.15" 
gem "sinatra", "0.9.4"
gem "webrat", "0.5.1" 
gem "sinatra_more"
gem "rack-flash"
gem "carrierwave"

only :test do 
	gem "warden", "0.8.1"
  gem "contest"
  gem "webrat"
  gem "shoulda"
  gem "redgreen"
  gem "override"
  gem "quietbacktrace"
  gem "do_sqlite3"
end
